- .github/workflows/openapi.yml
This PR keeps the repo up to date by automatically creating openapi pull requests.
> Add openapi pull request workflow

- bench/binary_size/Cargo.toml
- bench/binary_size/src/main.rs
- openapi/Cargo.toml
- openapi/src/main.rs
- src/lib.rs
- src/resources/event.rs
- src/resources/generated/placeholders.rs
- tests/encoding.rs
- tests/mock/mod.rs
This also removes and forbids unsafe code.
> Fix some unneeded clones and other clippy lints

- Cargo.toml
- examples/tokio/Cargo.toml
- src/client/blocking.rs
- src/client/tokio.rs
- src/resources/event.rs
This PR also bumps some dependencies. This closes #1
> Support tokio 1.0

- src/resources.rs
> Fix feature name account->connect, and link to issue for more context

- Cargo.toml
- openapi/src/main.rs
- src/client/tokio.rs
- src/resources.rs
- src/resources/generated/account.rs
- src/resources/generated/api_errors.rs
- src/resources/generated/balance_transaction.rs
- src/resources/generated/charge.rs
- src/resources/generated/customer.rs
- src/resources/generated/payment_intent.rs
- src/resources/generated/payment_method.rs
- src/resources/generated/payout.rs
- src/resources/generated/recipient.rs
- src/resources/generated/token.rs
- src/resources/setup_intent_ext.rs
This was the earlier commit that broke on the back, checking the automated testing stuff again.
> Updated after rebase, testing CI again, Enums and other stuff

- Cargo.toml
- src/resources/webhook_events.rs
Port of this PR: wyyerd/stripe-rs#210
> Drop subtle for the built-in constant-time verify_slice

- src/client/async_std.rs
- src/client/blocking.rs
- src/client/tokio.rs
- src/error.rs
- src/ids.rs
- src/params.rs
- src/resources.rs
- src/resources/generated.rs
- src/resources/generated/customer.rs
- src/resources/generated/invoice.rs
- src/resources/generated/invoiceitem.rs
- src/resources/generated/line_item.rs
- src/resources/generated/payment_intent.rs
- src/resources/generated/payment_method_options_boleto.rs
- src/resources/generated/payment_method_options_oxxo.rs
- src/resources/generated/product.rs
- src/resources/generated/quote.rs
- src/resources/generated/refund.rs
- src/resources/generated/subscription.rs
- src/resources/generated/subscription_schedule.rs
- src/resources/generated/test_helpers_test_clock.rs
- tests/customer.rs
Okay, this should be the final ready idempotency code.  Let me know if there are any issues.
> Development idempotency header

- Cargo.toml
- examples/webhook-actix.rs
Adds secure actix webhook example.
> Adding actix webhook example

- Cargo.toml
- src/client/base/tokio.rs
> Clean up dependencies

- .gitignore
- Cargo.toml
- src/client/base/async_std.rs
- src/client/base/tokio.rs
- src/client/stripe.rs
- src/error.rs
Adds path to `JSONSerialize` and `QueryStringSerialize` error
Fixes #205
> Add serde_path_to_error, Add path in JSONSerialize

- .github/workflows/async-stripe.yml
- openapi/Cargo.toml
Sorry for slow response, ref https://github.com/arlyon/async-stripe/pull/270#issuecomment-1235611922
> CI: Add fmt action separate from codegen verify

- .github/workflows/async-stripe.yml
- Cargo.toml
- README.md
Closes #220 (pending discussion there)
> Try bumping MSRV to 1.56

- README.md
> much -> must

- .github/workflows/release.yml
- .releaserc.json
> Automatic release

- src/resources.rs
> fix: reexport duplicate SubscriptionPaymentBehaviour

- examples/checkout.rs
- examples/customer.rs
- examples/payment-intent.rs
- examples/payment-link.rs
- examples/subscriptions.rs
> fix: Use `HashMap::from`

- Cargo.toml
> pin time-core to prevent msrv bump

- Cargo.toml
- examples/webhook-axum.rs
This PR updates the Axum example.
> chore: improve axum example

- src/resources.rs
- src/resources/transfer_reversal_ext.rs
Implemented `TransferReversal::create()`  method.
#399
> Implement transfer reversal

- Cargo.toml
> fix: Update hyper-rustls to fix RUSTSEC-2023-0052

- src/ids.rs
Add support for connect token ids, closing #423
> feat: add support for connect tokens

- src/ids.rs
> add support for atxi id prefix

- src/resources/invoice_ext.rs
Adds functionality to finalise an invoice as in https://stripe.com/docs/api/invoices/finalize #442
> finalize invoice

- openapi/Cargo.toml
- openapi/src/codegen.rs
- openapi/src/metadata.rs
- openapi/src/url_finder.rs
- src/ids.rs
- src/resources/generated/login_link.rs
- src/resources/generated/subscriptions_trials_resource_trial_settings.rs
> add plan to PriceId

- Cargo.toml
- examples/webhook-axum.rs
Re-push of #508 with a rebase. Closes #508, #473
> Fix: Repaired the Axum example

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/async-stripe.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/resources.rs
> bump msrv (closes #532)

- src/client/stripe.rs
> add clone docs for strategy (closes #520)

- .github/workflows/async-stripe.yml
- .github/workflows/openapi.yml
- .github/workflows/release.yml
- src/client/base/tokio.rs
- src/error.rs
- src/resources/balance_transaction_ext.rs
- src/resources/currency.rs
- tests/mock/mod.rs
> Fix semantic release

- .github/workflows/async-stripe.yml
- openapi/src/codegen.rs
- openapi/src/file_generator.rs
- openapi/src/main.rs
- openapi/src/metadata.rs
- openapi/src/url_finder.rs
- src/lib.rs
- src/resources/checkout_session_ext.rs
- src/resources/customer_ext.rs
- src/resources/setup_intent_ext.rs
> Clippy: leftovers, codegen

- src/ids.rs
> fix: rtx id prefix

- async-stripe-client-core/src/config.rs
> Add basic secret key sanity checks

- src/client/stripe.rs
Add some more docs for idempotency apis
> docs: add clone docs for strategy (closes #520)
