Cargo.toml
src/error.rs
src/resources/webhook_events.rs

Chrono is of course needed for Utc time. Don't code late at night!
This reverts commit e462ae4aef53a0f36d6fe6796820752490600335.

Revert "Remove dependency on chrono"

---

Cargo.toml
src/client/async_std.rs
src/client/blocking.rs
src/client/tokio.rs
src/error.rs
src/lib.rs
src/params.rs
src/resources/setup_intent_ext.rs

The goal of this PR is to clean up the error handling code.
This also as a side-effect removes most of the unwraps so that they are explicitly handled in cases where an error could actually occur, or `expect`ed otherwise.

Clean up error handling code

---

Cargo.toml
src/resources/webhook_events.rs

This also bumps the `hmac` crate
Closes #87

Introduce subtle and use it for constant time comparison

---

CONTRIBUTING.md
src/resources.rs
tests/plan_interval.rs

This reexports the various overlapping APIs with different names and adds tests to ensure they continue to work.
Closes #67 and closes #66

Api changes to resolve overlapping imports

---

src/resources/payment_method_ext.rs

Detach a PaymentMethod from a Customer api missing
[https://stripe.com/docs/api/payment_methods/detach](https://stripe.com/docs/api/payment_methods/detach)

Detach a PaymentMethod

---

src/client/async_std.rs
src/client/tokio.rs

This should reduce the code size and compile time of the monomorphized `send` functions.
See [Non-Generic Inner Functions](https://www.possiblerust.com/pattern/non-generic-inner-functions) for more details on the tactic.

fix: use non-generic inner function for send

---

src/lib.rs

This makes sure that the code examples in the docs should pass CI

Remove no_run annotation from doctests

---

src/error.rs
src/resources/charge_ext.rs

Adding account to charge source, as explained from the stripe docs below: 
A payment source to be charged. This can be the ID of a card (i.e., credit or debit card), a bank account, a source, a token, or a connected account. For certain sources—namely, cards, bank accounts, and attached sources—you must also pass the ID of the associated customer.
https://stripe.com/docs/api/charges/create#create_charge-source
Additionally adding the Hyper/Surf error message to the ClientError. 
PS.
Any ideas on adding Defaults to the library? Happy to do this if we come up with a good pattern. Currently something like below is not very pleasing to the eye:
```rust
create_checkout_session.payment_intent_data =
Box::new(Some(stripe::CreateCheckoutSessionPaymentIntentData {
application_fee_amount: …
```

Improving error reporting and adding account to charge_ext

---

.github/workflows/async-stripe.yml

As the adage says, you can't improve something you don't measure. So let's measure.

Use tarpaulin to measure code coverage

---

src/resources/webhook_events.rs

Async stripe can now parse setup intent events.
fix #169

Add setup intent event support for webhooks

---

src/resources/webhook_events.rs

Should be pretty simple and straightforward.
Types are listed here: https://stripe.com/docs/api/events/types

Add CheckoutSessionAsyncPaymentFailed/Succeded to Webhooks Events

---

src/resources/customer_ext.rs

#171 This basically adds the api for retrieving the customer payment .  Maybe in the future we take a crack at changing the way we generate the "function" calls of the API to get out more of the API without handwriting, but for now this is the fastest way to get certain features.

Customer Payment Method Retrieval

---

openapi/src/metadata.rs
src/ids.rs
src/resources/generated/application.rs
src/resources/generated/card.rs
src/resources/generated/connect_collection_transfer.rs
src/resources/generated/payment_intent.rs
src/resources/generated/payment_method_options_boleto.rs
src/resources/generated/payment_method_options_oxxo.rs
src/resources/generated/placeholders.rs
src/resources/generated/platform_tax_fee.rs
src/resources/generated/reserve_transaction.rs
src/resources/generated/tax_deducted_at_source.rs
tests/charge.rs

Turns out checking for x-resourceId is over-eager, and misses Ids that do not exist as root resource types.
See https://github.com/stripe/openapi/issues/83
Closes #183

Simplify the id heuristic to include non-root types

---

Makefile.toml

```
> cargo make duplicates
3 AccountRequirementsAlternative
3 AccountRequirementsError
3 AccountRequirementsErrorCode
2 AddInvoiceItems
2 Address
2 CapabilityStatus
2 CreditNoteTaxAmount
2 CustomerPaymentSourceCard
4 DiscountsResourceDiscountAmount
3 InvoiceItemPriceData
3 InvoiceItemPriceDataTaxBehavior
2 InvoicePaymentMethodOptionsCard
2 InvoicePaymentMethodOptionsCardRequestThreeDSecure
2 InvoiceSettingCustomField
3 LineItemsDiscountAmount
3 LineItemsTaxAmount
2 PaymentMethodOptionsBoleto
2 PaymentMethodOptionsOxxo
3 PlanInterval
2 SubscriptionItemPriceData
2 SubscriptionItemPriceDataRecurring
2 SubscriptionItemPriceDataTaxBehavior
2 SubscriptionPaymentBehavior
3 SubscriptionProrationBehavior
2 SubscriptionScheduleInvoiceSettings
2 TaxAmount
3 TaxIdType
2 TransferData
```

Add command to locate identical duplicate types

---

Cargo.toml
examples/customer.rs
src/params.rs

Fix list traversal

---

src/ids.rs
src/resources.rs
src/resources/generated.rs
src/resources/usage_record_ext.rs
tests/subscription_item.rs

See #213.
I tried to follow the existing code, but especially regarding the names of `CreateUsageRecord` and `UsageRecordAction` I'm not sure if those are the correct names to use to stay forwards compatible to what will eventually be generated automatically.

Expose UsageRecord and add UsageRecord::create extension

---

openapi/src/codegen.rs
openapi/src/metadata.rs
openapi/src/types.rs

This is a WIP to tackle the issue in #213 in deeper detail and begins by adding logging to determine which APIs are currently skipped over.
There are a number of creates, updates, and deletes that are miss-assigned causing clashes (as we currently only support one method per CRUD request) as well as a few unidentified methods that are neither a create or an update.
```
WARN stripe_openapi_codegen::codegen: unhandled CREATE for Account: POST /v1/accounts/{account}/bank_accounts (already have [List, Create, Retrieve, Update, Delete])    
WARN stripe_openapi_codegen::codegen: unhandled UPDATE for Account: POST /v1/accounts/{account}/bank_accounts/{id} (already have [List, Create, Retrieve, Update, Delete])    
WARN stripe_openapi_codegen::codegen: unhandled DELETE for Account: …
```

Begin work on supporting additional request methods

---

src/resources/webhook_events.rs

Add webhook event props

---

Cargo.toml

By default, `chrono` includes the feature `oldtime` which adds an extra dependency on an old version of the `time` crate. Since this crate only uses `chrono::Utc:now`, disabling this feature should be safe.

Avoid old time dep from chrono

---

Cargo.toml
openapi/version.json

`security-framework 2.7.0` requires 2021 edition, so trying to pin to fix CI

CI: pin deps requiring 2021 edition

---

src/ids.rs

Adds some of the remaining missing ids. Wasn't able to find anything for `CheckoutSessionItemId`, are those Line Items? https://stripe.com/docs/api/checkout/sessions/line_items

Add a few more missing ids

---

Makefile.toml

Saw this was added in https://github.com/arlyon/async-stripe/commit/d7a8a9f30bc6ca00f66633c92752d294be132c2e. Wanted to check if still necessary (seems fine locally), because I think it causes formatting issues in CI like https://github.com/arlyon/async-stripe/pull/261 because `RUST_FILES` is defined before the codegen step, then codegen creates a new file, but that new file is not included in `RUST_FILES`, so it is not properly formatted.

Remove RUST_FILES from fmt cmd

---

openapi/src/codegen.rs
openapi/src/util.rs

The idea here is to convert most of the repeated `out.push_str` logic into a more readable format-driven approach that makes it clearer what rust code is actually being generated. This PR is a smaller piece broken off from a larger PR towards that goal for ease of review. 
The long-term goal is to make it simpler to separate the logic of writing out generated code  from reading the spec so that eventually the codegen process can look more like 
`Parse spec` -> 
`convert to some kind of intermediate representation specifying what to generate` -> `generate the rust files`
instead of all steps happening simultaneously.

CLN: format more instead of push_str in codegen

---

src/ids.rs

`POST /v1/refunds` returns the following Refund object with an ID the has the prefix `pyr_`
```
{
"id": "pyr_XXXXXXXXXXXXXXXX",
"object": "refund",
"amount": 322,
"balance_transaction": "txn_XXXXXXXXXXXXXXXX",
"charge": ["py_XXXXXXXXXXXXXXXX"],
"created": 1661959715,
"currency": "usd",
"metadata": {},
"payment_intent": ["pi_XXXXXXXXXXXXXXXX"],
"reason": null,
"receipt_number": null,
"source_transfer_reversal": null,
"status": "pending",
"transfer_reversal": null
}
```
This `pyr_` is not a defined ID for Refund objects in the `src/ids.rs` file, resulting in an error when fetching this object from Stripe. I cannot find documentation that points to this prefix (as with most Stripe prefixes), but I'm guessing it denotes a refund (r) from a PaymentIntent charge (py), which is the case in my …

fix(prefixes): add pyr_ prefix to Refund object

---

src/resources/setup_intent_ext.rs

Hi!
This implements cancel for SetupIntents. The API is very similar to cancel for PaymentIntents.
Fixes #266.

Add cancel SetupIntent

---

openapi/src/mappings.rs
openapi/src/metadata.rs

This changes the old format for instantiating Maps from `.iter().cloned().collect()` to the new `BTreeMap::from` syntax introduced in Rust 1.56.
Please feel free to reject if this jump in MSRV (1.49 -> 1.56) is too large - just a QOL change I spotted digging around the codebase.

Updating BTreeMap::from to Rust 1.56 syntax

---

src/lib.rs

Inspired by an error I saw when using https://github.com/launchbadge/sqlx. Hopefully gives a bit quicker feedback about how to solve an otherwise giant compilation error when forgetting to specify a runtime feature, though could still be improved as mentioned in the comment.

Emit compile error when no runtime feature specified

---

.github/workflows/async-stripe.yml
Cargo.toml
src/params.rs

Since the `tokio::test` macro is in `tokio` which is already a dev dep, can avoid needing `tokio-test` as well with a small doctest change

Remove tokio-test dep

---

.github/workflows/async-stripe.yml
src/client/base/tokio.rs
src/resources/webhook_events.rs
tests/subscription_item.rs

This was the approach for denying warnings recommended by https://matklad.github.io/2021/09/04/fast-rust-builds.html (there are other potential CI neat tricks in there as well)
Should ensure that in future releases building with the `async-stripe` dep won't leak any warnings to the end-user (like the current `v0` unused)

Deny build/test warnings in CI

---

src/client/base/tokio.rs
src/client/base/tokio_blocking.rs
src/error.rs
src/ids.rs

My team's encountered a number of issues with stripe, which we've already implemented fixes for in stripe-rs. We're planning to migrate to async-stripe, so I'm opening this PR to upstream those fixes.
- Add BankAccountVerificationFailed to ErrorCode enum - https://github.com/wyyerd/stripe-rs/commit/9a17aaebb4970080eb452ec43d8406e94eb3f1d9
- not much to say about this one. it can be returned, and we've had to handle it in the past
- Add `prefixes` and `is_valid_prefix` methods to better support ids with multiple valid prefixes - https://github.com/wyyerd/stripe-rs/pull/171/commits/30f10149c77e4cb2a437d1de6f9cd0236197a1f6
- Allow tokio clients to be used in multi-threaded scenarios - https://github.com/wyyerd/stripe-rs/pull/171/commits/b5ad42bebe680c394b2c3c46326924d4f8c22b71
- Disable …

upstream fixes from stripe-rs to async-stripe

---

src/params.rs

Perhaps this should be replaced with something configurable, like `tracing::debug`?
Signed-off-by: Sean Pianka <pianka@eml.cc>

fix(params): do not print "next" while iterating

---

src/ids.rs

Been starting to look at using `miniserde` in place of `serde` for deserialization to help compilation times. One place where `miniserde` `Deserialize` implementations would need to be hand-written is with the ID handling so just wanted to add some tests to confirm behavior since hopefully those tests would be useful regardless.

Add some ser de testing for ids

---

src/error.rs

When calling the [UsageRecord::create](https://docs.rs/async-stripe/latest/stripe/struct.UsageRecord.html#method.create) function I get this error:
```
JSONSerialize(Error("unknown variant `idempotency_error`, expected one of `api_error`, `api_connection_error`, `authentication_error`, `card_error`, `invalid_request_error`, `rate_limit_error`, `validation_error`"))
```
I initialize the client with the strategy `stripe::RequestStrategy::Idempotent`.
I guess the fix is to add the `idempotency_error` to this enum.

fix: add idempotency_error

---

.github/workflows/release.yml
.releaserc.json

Adds a new automated release config that will push new versions to cargo on every commit to main.

fix: add automated release config

---

.github/workflows/async-stripe.yml
.github/workflows/openapi.yml

Replace cargo make install action with a cached prebuilt version.

use prebuilt cargo-make in CI

---

openapi/src/url_finder.rs
src/resources/generated/balance.rs
src/resources/generated/capability.rs
src/resources/generated/cash_balance.rs
src/resources/generated/checkout_session.rs
src/resources/generated/credit_note_line_item.rs
src/resources/generated/customer_cash_balance_transaction.rs
src/resources/generated/financial_connections_account.rs
src/resources/generated/financial_connections_session.rs
src/resources/generated/identity_verification_report.rs
src/resources/generated/identity_verification_session.rs
src/resources/generated/issuing_authorization.rs
src/resources/generated/issuing_card.rs
src/resources/generated/issuing_cardholder.rs
src/resources/generated/issuing_dispute.rs
src/resources/generated/issuing_transaction.rs
src/resources/generated/login_link.rs
src/resources/generated/payment_link.rs
src/resources/generated/radar_value_list.rs
src/resources/generated/radar_value_list_item.rs
src/resources/generated/reporting_report_run.rs
src/resources/generated/reporting_report_type.rs
src/resources/generated/review.rs
src/resources/generated/scheduled_query_run.rs
src/resources/generated/tax_id.rs
src/resources/generated/terminal_configuration.rs
src/resources/generated/terminal_connection_token.rs
src/resources/generated/terminal_location.rs
src/resources/generated/terminal_reader.rs

Improves the url finding code in the codegen such that we cover more of the (and fix broken) urls. Closes #326.

feat: improve api doc code to fix / add more coverage

---

src/resources/checkout_session_ext.rs

fn to expire checkout sessions

---

Cargo.toml

Closes #333. Rustdoc examples scraping is now turned on by default. https://github.com/rust-lang/docs.rs/pull/1954

remove cargo args

---

src/ids.rs

Adds the missing "li_" prefix for CheckoutSessionItemId.
This can be seen in the documentation here:
https://stripe.com/docs/api/checkout/sessions/line_items
I also see the same prefix with the Stripe CLI, using `stripe checkout sessions list --expand data.line_items`

Add missing prefix for CheckoutSessionItemId

---

src/ids.rs
src/resources.rs
src/resources/credit_note_ext.rs
src/resources/customer_balance_transaction_ext.rs
src/resources/generated.rs
src/resources/generated/credit_note.rs
src/resources/generated/credit_note_line_item.rs
src/resources/generated/customer_balance_transaction.rs

Adds support for `CreditNote` and `CustomerBalanceTransaction` objects, which are different ways of applying credit to a customer account.
I wasn't sure whether `CustomerBalanceTransaction` actions (create, list, etc.) should be methods of `Customer` or of `CustomerBalanceTransaction`; since they have the customer id in the API path, I chose to make them part of `Customer` but left them in a separate module `customer_balance_transaction_ext.rs`. It would be easy to change either of those decisions if you disagree.
Note: this adopts 3 previously-unused generated modules, which means that `cargo make fmt` saw them for the first time. I'm not sure if committing those formatting changes is the right step, but I included that as a separate commit.

add CreditNote and CustomerBalanceTransaction

---

openapi/src/util.rs
src/lib.rs
src/resources/generated/capability.rs
src/resources/generated/issuing_card.rs

Adds a brief blurb for idempotency in the docs for the main lib, with links to the relevant apis.
Closes #342

Idempotency notes

---

src/ids.rs

Adds the `sis_` id as an option for `UsageRecordSummaryId`s, as seen in the Stripe API docs - see the Response example at https://stripe.com/docs/api/usage_records/subscription_item_summary_list

fix: Add sis_ id prefix for usage record summaries

---

Cargo.toml
src/ids.rs
src/resources.rs
src/resources/generated.rs
src/resources/generated/tax_calculation.rs
src/resources/generated/tax_calculation_line_item.rs
src/resources/generated/tax_product_resource_customer_details.rs

Exposes the tax calculation API as requested in https://github.com/arlyon/async-stripe/discussions/365

feat: add tax calculation api behind a feature

---

src/resources/webhook_events.rs

Added webhook event types for "customer.subscription.created" and "customer.subscription.paused" events.

Added webhook event types

---

src/resources/webhook_events.rs

Added attribute for previous event object in webhook events. Used a `HashMap<String, Value>` to represent it but I am not sure if this is a good choice. My reasoning is that not all attributes of the object are present, only ones that have been updated, so deserializing to a specific EventObject variant may not be a good fit as all the attributes in the EventObject struct will need to be iterated to check which ones are set. Additionally, since the developer doesn't know which attributes will be updated, it is best to keep the entries flexible and let the developer choose how to access the data in `"previous_attributes"` depending on the attributes present. 
Open to feedback. Thanks!

Added attribute for previous event object

---

Cargo.toml

fix: don't pin time-core for msrv

---

src/client/base/tokio.rs

We had a panic in production because of a well known issue in `http_types` where StatusCode conversion can panic:
* https://github.com/http-rs/http-types/issues/183
A proper fix probably involves switching away from `http_types` entirely, but I interrupted my initial attempt because that requires changes all over the code base (replacing `Request`, `Method`, `Url` and `Body` types).
Therefore I'm submitting this quick fix which just avoids the code path with the `unwrap`.

Fix panic in tokio client when encountering unsupported StatusCode

---

openapi/src/codegen.rs
src/resources/generated/price.rs

This PR adds a check to verify if the `ty` is already a `CurrencyMap` to avoid generating any nested `Option<CurrencyMap<...>>` as shown on #480 .
On a side note: this is something that will also be fixed on #452.
Closes #480 
Closes #427

fix: avoid generating nested currency options map

---

examples/checkout.rs

Fixes the typo `exmaple` in the `checkout.rs` file.

Fixed typo in checkout.rs

---

examples/connect.rs
src/params.rs

- [ X ] ran `cargo make fmt`
- [ X ] using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to hightlight user-facing fixes and features
fix: Fixed infinite loop on list pagination when the result had more than 1 item
I also added tests with 2 elements, so this never happens again.
What was happening: 
The `get_data` implementations of `PaginableList` was cloning the data every single time.
When the data was "popped" in the `unfold_stream` function, it was popping from the cloned vector.
Specifically the `if paginator.page.data.len() > 1 { ...` as with anything less than than 2 elements, the condition was false and it either ended the stream or requested the next page.

Fixed infinite loop on list pagination when the result had more than 1 item

---

openapi/src/metadata.rs
src/resources/currency.rs

fixes #459 
(Most of the changes come from fmt)

Add missing  byn and mmk currency in the Currency enum

---

src/ids.rs

Adds support for `pdp_` as an id prefix for dispute objects. We encountered this prefix in the wild as a dispute on an ACH payment made via payment intents.

fix: support pdp_ as an id prefix for dispute objects

---

src/resources/subscription_ext.rs

Same as #402. Accidentally closed. Sorry!
A fix for #394
https://stripe.com/docs/api/subscriptions/cancel
According to the current Stripe API in the link above, there is no "reason" field within cancellation_details any longer. This also aligns with my testing where it did not recognize the parameter.
Consider removing this struct in future versions. For now, users can leave this as None.
- Replaced `at_period_end` with `invoice_now`
- Added `cancellation_details` field
- Added `prorate` field

Corrected CancelSubscription fields for current Stripe API version.

---

src/resources/invoice_ext.rs

This pull request exposes the `auto_advance` field from the `FinalizeInvoiceParams` struct, allowing users to access it outside its defining module.

Expose the `auto_advance` field from the `FinalizeInvoiceParams` struct

---

Cargo.toml
examples/checkout.rs
openapi/src/codegen.rs
src/resources/generated/account.rs
src/resources/generated/charge.rs
src/resources/generated/checkout_session.rs
src/resources/generated/customer.rs
src/resources/generated/file.rs
src/resources/generated/invoice.rs
src/resources/generated/payment_link.rs
src/resources/generated/quote.rs
src/resources/generated/radar_value_list.rs
src/resources/generated/tax_calculation.rs
src/resources/generated/tax_id.rs
src/resources/generated/tax_transaction.rs
src/resources/generated/treasury_transaction.rs

We were special casing optional lists, rather than following the spec. This code path has been around forever and has likely been invalid. This is a breaking change.
Closes https://github.com/arlyon/async-stripe/issues/456 and https://github.com/arlyon/async-stripe/issues/496

fix: correctly generate types for optional lists

---

src/resources/setup_intent_ext.rs

As raised on https://github.com/arlyon/async-stripe/issues/504, this attribute have the incorrect name according to the [documentation](https://docs.stripe.com/api/setup_intents/confirm#confirm_setup_intent-return_url). This change renames the field `redirect_url` to `return_url`.
closes #504

fix: rename redirect_url to return_url on ConfirmSetupIntent

---

src/error.rs

The Display implementation for RequestError previously was:
```
invalid_request_error (400) with message: Some("Product already exists.")
invalid_request_error (400) with message: None
```
This PR changes it to:
```
invalid_request_error (400) with message: "Product already exists."
invalid_request_error (400)
```
Goal is to be shorter and look a bit friendlier.
Thanks for this library! Lmk if you'd like any changes (or edits by maintainers is also enabled).

fix: Remove "Some()" from RequestError's display

---

src/resources/webhook_events.rs

feat(webhook_events): support construct_event with timestamp

---

async-stripe/src/client/headers.rs
async-stripe/src/client/stripe.rs
openapi/src/url_finder.rs
stripe_webhook/src/webhook.rs

After the big PR in, excited for a small, self-contained PR with some small tweaks I didn't want to mix with everything else

Simplify client, remove some allocations

---

src/resources/checkout_session_ext.rs

Add missing method for checkout session
https://docs.stripe.com/api/checkout/sessions/line_items

Add `retrieve_line_items` function for `CheckoutSession`

---

src/resources/customer_ext.rs
src/resources/setup_intent_ext.rs

Adds a field for confirming a setup intent and providing the mandate that the customer used to confirm. 
Adds a new method for verifying a setup intent created as a us_bank_account with microdeposits.
Fixes a parameter to be optional when querying for all customer payment methods.

feat(setup_intent): add mandate_data for confirm

---

async-stripe-client-core/Cargo.toml
openapi/Cargo.toml

A call to tracing:: was added on https://github.com/arlyon/async-stripe/pull/576 but the dependency seems to be missing, which causes the branch to not compile at the moment.
https://github.com/arlyon/async-stripe/blob/2b918fe596fd01f183bb944df59650ad9128342b/async-stripe-client-core/src/config.rs#L42-L44
---
Also bumped bump tracing from `0.1.36` to `0.1.40` on `openapi`.

fix(client-core): add tracing dependency 

---

src/lib.rs

Similar to the work done for the [`next`](https://github.com/arlyon/async-stripe/tree/next) branch on https://github.com/arlyon/async-stripe/pull/582, this fixed the Clippy warning about [lazy doc continuation](https://rust-lang.github.io/rust-clippy/master/index.html#/doc_lazy_continuation).
This should fix issues with the pipeline for other PR's, like this one: https://github.com/arlyon/async-stripe/actions/runs/10114673863/job/27973827484

fix(master): linting issue from Rust 1.80

---

Cargo.toml
examples/test-clocks.rs
src/resources.rs
src/resources/test_clock_ext.rs

This adds support to the following `TestClock` operations:
- [Create](https://docs.stripe.com/api/test_clocks/create)
- [Retrieve](https://docs.stripe.com/api/test_clocks/retrieve)
- [List](https://docs.stripe.com/api/test_clocks/list)
- [Delete](https://docs.stripe.com/api/test_clocks/delete)
- [Update](https://docs.stripe.com/api/test_clocks/advance)
Closes #574

feat: add support for TestClock operations

---

async-stripe-webhook/Cargo.toml
async-stripe-webhook/src/webhook.rs
async-stripe/src/lib.rs
generated/async-stripe-shared/src/invoice.rs
openapi/src/templates/utils.rs

This applies fixes for issues that are introduced by the new version of Rust: [1.80](https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html).
These are the following:
- [Lazy doc continuation](https://rust-lang.github.io/rust-clippy/master/index.html#/doc_lazy_continuation): 
> In CommonMark Markdown, the language used to write doc comments, a paragraph nested within a list or block quote does not need any line after the first one to be indented or marked. The specification calls this a “lazy paragraph continuation.”
To avoid confusion, this means that multilines now need to be explicit. The two cases where that is the case today is for the docs on the [`async-stripe/src/lib.rs`](https://github.com/arlyon/async-stripe/blob/54553bf596a06d08c52973410c01bb9999b1401a/async-stripe/src/lib.rs#L5 …

fix(next): linting issues from Rust 1.80

---

src/resources.rs
src/resources/promotion_code_ext.rs

This PR enables users of `async-stripe` to create promotion codes.
I needed to programmatically create a lot of promotion codes, and since I couldn't find a way to achieve this with `async-stripe`, I've added it manually.

Add "create promotion code" API

---

README.md

We should make people aware the next branch is a thing.

mention next branch in readme

---

generated/async-stripe-billing/src/invoice/requests.rs
generated/async-stripe-billing/src/plan/requests.rs
generated/async-stripe-billing/src/quote/requests.rs
generated/async-stripe-billing/src/subscription/requests.rs
generated/async-stripe-billing/src/subscription_schedule/requests.rs
generated/async-stripe-billing/src/usage_record/requests.rs
generated/async-stripe-connect/src/account/requests.rs
generated/async-stripe-core/src/file_link/requests.rs
generated/async-stripe-core/src/payment_intent/requests.rs
generated/async-stripe-core/src/setup_intent/requests.rs
generated/async-stripe-core/src/token/requests.rs
generated/async-stripe-misc/src/tax_registration/requests.rs
generated/async-stripe-payment/src/payment_method/requests.rs
generated/async-stripe-product/src/price/requests.rs
generated/async-stripe-product/src/product/requests.rs
openapi/src/templates/enums.rs
tests/tests/it/enums.rs

This pull request closes #604 by properly generating enums.

fix(next): enum serialization

---

openapi/src/url_finder.rs
src/resources/generated/payment_link.rs

The Stripe documentation now is hosted on `https://docs.stripe.com/api`. The old `https://stripe.com/docs/api` still works but gets redirected to the new one.
The issue is with how we use to generate documentation link on `url_finder.rs`. On that file, we look for the load the docs and find the `window.__INITIAL_STATE__`, which contains relative links to the resources.
We are using those relative links as if they were relative from `https://stripe.com`, but now they are relative from `https://docs.stripe.com ` which causes the links to not be correctly built.
This is the issue that is causing the `verify-codegen` CI job to fail.
By updating it to the right path, it should stop generating incorrect path to the docs.

fix: correct docs path for references

---

async-stripe-webhook/src/webhook.rs

Added a new method to parse a webhook event without validating the secret.
I've named the method `Webhook::insecure` to make it clear that it's not secure to use it, must be used for local testing only and a link to the method to be used in production.
Some of the use cases are:
- Early stages of development
- Automating a local testing environment using the stripe cli listen command to forward events, when there is no way of retrieving the secret from the listen output to use in the integration

feat(next): parse a webhook event without the secret

---

src/lib.rs

I wasn't sure which features we want to add to `package.metadata.docs.rs` in `Cargo.toml` since the key already exists and only includes `runtime-tokio-hyper`.

Enable rustdoc cfg feature

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/async-stripe.yml
.github/workflows/release.yml
Cargo.toml
README.md
src/client/stripe.rs
src/resources/payment_source.rs
tests/encoding.rs

Also fixes some new lints from new rust compiler versions and re-enables a test that was accidentally not being run.

bump msrv since openssl fails to compile

---

.github/workflows/async-stripe.yml
.github/workflows/public-api.yml

Observations:
* I omitted auto derived impls and blanket impls, which brought down the api json file from 25mb to 7mb
* `cargo public-api diff` does not work, I couldn't get features to be passed to diff (opened an issue for this)
* The test workflow would work, however, the output is not diffed and the file is 7mb. So this file would have to be diffed manually and the pipeline would always just report "not the same". Maybe there is some nice diff tool that can be used to generate a diff in the pipeline. 
Open questions:
* Does public-api exposes some api to generate the diff programatically?
* Which features do we want to use to check this? 
* With diff we could check the whole matrix
* With the test approach every combination of features will need a dedicated file which adds up quickly …

Public api

---

src/resources.rs

Currently, the `checkout_session_ext` is not being exported, which makes the `RetrieveCheckoutSessionLineItems` not being able to be used.
With this change, the following should now be possible:
```rust
use std::str::FromStr;
use stripe::{CheckoutSession, CheckoutSessionId, Client, RetrieveCheckoutSessionLineItems};
#[tokio::main]
async fn main() {
let secret_key = std::env::var("STRIPE_SECRET_KEY").expect("Missing STRIPE_SECRET_KEY in env");
let client = Client::new(secret_key);
let _line_items = CheckoutSession::retrieve_line_items(
&client,
&CheckoutSessionId::from_str("").unwrap(),
&RetrieveCheckoutSessionLineItems::default(),
)
.await
.unwrap();
}
```
Closes #614

feat: export checkout_session_ext

---

async-stripe-webhook/src/lib.rs

Expose `webhook::EventData` so that we can create webhook events from other crates, mainly to perform testing.

feat(next): expose webhook event data

---

async-stripe-webhook/src/generated/mod.rs
async-stripe-webhook/src/webhook.rs
openapi/src/webhook.rs

It's recommended to process stripe webhook events asynchronously ([doc](https://docs.stripe.com/webhooks#handle-events-asynchronously)), so it will be common to write those events to some kind of pub/pub like kafka.
This PR derives the serialize and deserialize traits on the webhook event when the feature flags are enabled.

feat(next): Serialize and deserialize webhook events

---

.github/workflows/async-stripe.yml
async-stripe/src/hyper/client.rs
async-stripe/src/lib.rs

Hi, first of all - amazing work what you've done on the next branch. The api is absolutely amazing, but it still has some rough edges.
I've done one integration on 0.40 and now I'm building another integration and I've decided to use the next branch, so that I can test its ergonomics and help to improve it.
I would consider this PR a draft for now, because I'm just starting with the integration and I probably will send more patches if something doesn't work or doesn't seem right.
For now this PR contains two small commits - everything is explained in detail in the commit message as to why I've done it, but here is a list of things I've done (I will be editing this list with the new patches as I create them):
- export `StripeRequest` trait - allow `.customize()` to be used outside this …

small functional improvements

---

async-stripe-webhook/Cargo.toml

Refs: https://github.com/arlyon/async-stripe/issues/663
When I enabled `serialize` or `deserialize` feature flag on `async-stripe-webhook` with some kind of extra dependency (for example `async-stripe-checkout`), it resulted in compilation error, because `serialize` feature was not enabled on any of those extra packages

fix(webhook): Correctly enable serialize feature on all enabled crates

---

src/resources/webhook_events.rs

Using `EventType::to_string` was returning a string that started and ended with quotation marks due to how it was using serde_json to generate the string.
This tripped me up because I was using `.starts_with("customer.subscription")` for handling subscription events which failed until I changed it to `.starts_with("\"customer.subscription")`
This PR changes the Display implementation to use the [serde::Serializer implementation for std::fmt::Formatter](https://docs.rs/serde/1.0.219/serde/trait.Serializer.html#impl-Serializer-for-%26mut+Formatter%3C'a%3E)
instead of involving serde_json. This makes it not have the quotes (see the included test) and has the added benefit of removing a possible panic since the error returned by the formatter's serializer can be returned directly.
Note that …

fix: Remove quotes from EventType display 

---

examples/webhook-axum/Cargo.toml
examples/webhook-axum/src/main.rs

Bumps Axum to 0.8 on the `webhook-axum` example. This bump requires the removal of #[async_trait] as pointed out on #712.
Close #712

chore(webhook-axum): bump Axum to 0.8.4

---

async-stripe-client-core/src/request_strategy.rs

I started using the `next` branch and whilst migrating my code I found myself writing a lot of the following:
```rust
let customer = CreateCustomer::new()
.email(user.email)
.name(user.name)
.customize()
.request_strategy(RequestStrategy::Idempotent(
IdempotencyKey::try_from(user_id.to_string())
.expect("Uuid is always valid IdempotencyKey"),
))
.send(stripe_client)
.await?;
```
Due to the `IdempotencyKey` not being just a `String` anymore but a newtype with length validation in its `TryFrom<String>` implementation. 
The new `From<Uuid>` impl will allow just writing:
```rust
let customer = CreateCustomer::new()
.email(user.email)
.name(user.name)
.customize()
.request_strategy(RequestStrategy::Idempotent(user_id.into()))
.send(stripe_client)
.await?;
```
- [ x] ran `cargo make fmt`
- [x ] …

add From<Uuid> implementation for IdempotencyKey

---

async-stripe-client-core/src/pagination.rs
async-stripe-types/src/pagination.rs

Replacing #709, rebased on latest API changes

Remove unused `total_count` field from `List`
